spring:
  profiles.active: cloud
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false
logging.level:
  microsec.freddysbbq: DEBUG
  org.springframework:
    cloud:
      sleuth: INFO
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: 8080
    securePortEnabled: false
    securePort: 61001
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
