spring:
  profiles.active: cloud
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false
logging.level:
  org.springframework:
    cloud:
      sleuth: DEBUG
management:
  security:
    roles: order.admin
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: true
