server:
  port: ${PORT:0}

spring:
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      keys-to-sanitize:  pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: INFO

sfdc:
  client_id: '{cipher}AQBQKv2ZP9ATFO27/Y1oSH/1/DlJWm2kWQ01x3oFZ0s72sI9JzzTuTWpEWdfjtpg4SBQQYUNog2Ks/HwaM8bzynNs3Pusgqxu7EbipP9O2jr0mDb+/wR9/6Bo4QFkQYejB+bEIsb1CR+m56aaXsVni3IvNPLPorNKmHtiegMNmiKzrW3ccIN3A4QYrF0GB8iSfhUN9ZEcWn7JTn0BnUB661DlH3NMIlxyn+zWFzPEgOuGPU8kgqv/K2bdKS1/4kyfnFlaiqDbAosqrlZBH9nfVuEl7/zSL0d1ovRNUuHG3F9dT4R+LIHgkfsCZLiDkR0ai4Q4uy884hFLEY/0TiNJZYvCAedjQedfqu6b5MavD3nxrro5nvSdCseFPe3dRJ58pb84VX5MrcrrFc0+JE+VBd5psDc2AeKIrNnGmcFIrL0+Csqro2CjwLi3hpKtP+l1z6QgJR+y3jW4nW7vbaOCE03c0owRObFsAbDzrf7h6WKIw=='
  client_key: '{cipher}AQBfUc/p/Nn1g5U0j55P2ALcOL5BCJJGQNXixdhU99nIpFr6folSyb9rF1i/pnt8fABTtAxh1hnvIN0ohHGlzI1ZrRFiBZKlSkmQ78TI9z8k4mtqw6Xzu27xaKhTGjAV2G7TMRM1FIFDXQJ+b1QvM8SoVTR/rg5y3dVnDM6MP8EQF6HCz5tiJLsHtBFbZY5yhjpmn/bCpU04MyUxCRxh1yexWW6mR1/Bi49DcwHbkXgGhYFzI6bHBHi+CUFFKsI8NXtvlJb/pT3YTQOEZDD/WeZjUoyQRwPgFBWMmdqy8yRvSA9YJuiq49d53Zis6+DAx7evc8LnzYeWxjN6mWVx5R2XSNPm+S579kgQ74+DEHNzI6CqQW9pPji33kjnu6gis9ybiqlB08N9zq3jhMdsRrsy'
  uid: '{cipher}AQCaC3mkEo0faiYSH5liu8fGE0zFy18ta8nozrPPxEGW7xLD6M7r6IlXzKMYj6eMUzoIuL3hBIfM759FkrcPU6GhtbfOwE9oMq5gqk+jlDlB5+f/hNSrAUWPVxfY82DlpRSv8OIr4CyXinzWHK6iKPxRUvXOOtheo//agWsNPGEUSseWfqyURqi7xA31/dqSgmWUqhKL/U18+vs5VcJZu/fmVz88Yp5mLeUoTqhO/wbmilDd/mLUFQJavyXV+6qY2WqgvFEQCOTue80nKqS+9KDS7YJYN+ugafMkqB8+27CvUDbdNRqfwynzUt1uPFANwJd4lUTH78h3KG7jKLQ9bawar25mf8KqrvIQ2hTvUA+wz4EX4l9uiTYQEkFYoI0SMI6goGAS3tisHHsvVT4n3n7j'
  pwd: '{cipher}AQBtMKDNeWzmu+u232nu9FoHRyPxKP2eZKzeTPkTxBEWvhpnrqDheMry7WMrNkoq+Twnyi21fPE9NmkyrUNBmf130hRYruse82jwANE5jYKQTtg96h/jGFop35FAH4XsUvqLL7fQCLPgV00KWusRQGO2c4/X6I8DAbh8A5+MYXm62BZxRPWgE6zg4KFBWCsKvNJXTr3vI33AFNn/1T4FwZ+0sE/e0US0VvBtwim74vF6wQIAEO5mwzhREdSf0zNpWsEemXPp4xWUs3NT3mey07FFo8K0dqBY1gD0X7w7EQ391ly+XgBvrfPeLeIZIC8/w5k274UecJxDhJt5+DBul0AjwIPODnNAltwn+uw5kDIUe149SmxVlk3pCG6BmOfCiGM/fY3mfXNYtL4tcWWcPhK8sQke12rJ+RR8bSXxThn4VQ=='

---
spring:
  profiles: local
  # instance:
  #   nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: authservice
    # nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

# sfdc:
#   client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
#   client_key: 4631320832041516337
#   uid: jigsheth@sfdc.com
#   pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3
