spring:
  profiles.active: cloud
security:
  basic:
    enabled: false
management:
  context-path: /manage
  security:
    enabled: false
endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex
logging:
  level:
    org.springframework.cloud: INFO
    com.couchbase: DEBUG

couchbase:
  bucket: beer-sample
  password:
#  nodes: 192.168.99.100

---
spring:
  profiles: cloud # For deployment in Cloud Foundry  
