---
spring:
  profiles: development

user:
  role: Developer
  password: '{cipher}AgCGgPrABEEjE51RIgVU9D+R4pWc4KJjvEc8HriZ++yUHEzeha9mfaqZaVKqS8BRIgyhXRQWO6Uiib9K+RjhGGfuc6upOXdai05fOqdsxEBUxgdHtwLTarakshTKVCteAbfXxzYVpfbCPkxqGWRh+utJFrhX3k3eyEVTHLOx7wmpmIrUOKXmGkume9PqvjvXnR6nDwqQ1Kd8DQ8kz/dSPkJncPrUnF8JZ37CZcbE+x8GQ+lW9br88TVOFiEYJN2kfA40klKA3aYpr95NgA5PkkmtGC1FgGbeRTFvP9Jgr+Xjc4+897iSGyG4YBqMb+ZzRbcJvbn1ilwzE5EYOu9OoO9WVL3jvOT14JrsLLGaIQIAlnzsrle1LN2nfWklW25MSGYzrAlPmnj15sf5zh6P7UwivYKmCIH9KCXiC5XzlWB17I7oAd41bdrw1g/AbAh2oAzvz6/pGuiY1yaJoyldq9fXAg99homPF1Tq77zOHS4Xi5G2M561LTzTkKxzYZmOQMGUAAzPUVtD+sFzKjRXy7oO7IxlosTg6t5JyB+YC6tjsi7O07GAvBtsgveDTUiZ9e+2eIi6Zp4IltPGB81AKQ6fNk4GIEU3PLZAi21VvHXqxgmYfmwzEXBEs4i8Iw9wEQ3tKzxWklQFiIgkjWhx9KLDYm/NXRvdwJV7sw5ZydoEyk26RnuHBtPQqAORIHlFKcsCqi0tndRS1UvMVZ3/bRff'
---
spring:
  profiles: production
user:
  role: Production
  password: '{cipher}AgBx0nfvpCYZdXMI40g+RuIoB26gnrgQXKB28Dtx8pmqg/V9ua8ory7oFOgQPfcNAu2Ka206OE5mL90i62qb0DXNd2pl8Gta2Ygu0z5ClxeO40x5PNw+4M3DOfXFm9RZzsqLEcQiLCkjSkRoEUFEFN6Gsre657xHUW1/TyaT1x1xYC0sNnnzXWMoQsko+4o9Unl1MH/v3i4khtT4Z2/9F2kudLFpaPfcQHy0bmMKJESJErUgnoimezsO7kiP8u5LaEmEDyPHj3hv5oMhB8AYCVwyOWPQGVHb3qeICWub8/90Yq3Ty5L8AZR2N3C13nJrpEJrWEnZYD+mP91xZCkGM9DKHdg3Bi7h6P5jZdJm5eYLoHnxrZzUX9CiY+UKlTutcO0+Uy273zG5a59HalY2V8T6FZOqIXKFDzW2QHljag8UDkehF/TQc3Gb1BcJPo7Yigr4ll3haoPKwTsVUzeDyjbI2BAgaKtUxzei5q5rcPPh/teUXazHaWAzedyVXYIDCGRmUMv8z2ZxZl7Is1x45t2XLiimIOD2KBJszeKu+PrOg9I5glBSw0oFeJkyFAW65qFspPMeUjC1+i7gyPBovU1bEQTVhBg81/vBEhmMTgvJyN147/gzGoB6JofKpwaB+IhZP5a1h3akjv2LHFXriUFO41dUM0mEd2XoHZ9w/aL6ZpDgCK8TPtWkgJ/MAhBe65Bd0usHcU889y2CiduIrnOw'
