spring:
  profiles.active: cloud
  sleuth.sampler.percentage: 1.0
  sleuth.sampler.probability: 1.0
  zipkin.sender.type: rabbit
server:
  port: ${PORT:0}
security:
  basic:
    enabled: false
management:
  cloudfoundry:
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: admin
      show-details: always

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.springframework.cloud: ERROR
    microsec.freddysbbq: DEBUG
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      # registrationMethod: route
      registrationMethod: direct
eureka:
  instance:
    nonSecurePortEnabled: false
    nonSecurePort: 8080
    securePortEnabled: true
    securePort: 61001
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: true
