spring:
  profiles.active: cloud
server:
  port: ${PORT:9000}
security:
  basic:
    enabled: false
  user:
    name: admin
    password: pivotal
    roles: USER

welcome:
  msg: 'welcome to Pivotal'


---
spring:
  profiles: cloud # For deployment in Cloud Foundry
