server:
  port: ${PORT:9000}

spring:
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: pivotal
      roles: USER

welcome:
  msg: 'welcome to my world.'

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
