spring:
  profiles.active: cloud
server:
  port: ${PORT:9000}
security:
  basic:
    enabled: false
welcome:
  msg: 'welcome to my world@!'
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
