server:
  port: ${PORT:0}

spring:
  sleuth.sampler.percentage: 1.0
  zipkin.sender.type: rabbit

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      keys-to-sanitize:  pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: DEBUG

info:
  component: Opportunity Service
  app:
    name: ${project.name:opportunityService}
    description: ${project.description:SFDC Opportunity Service}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.sfdc}
    artifact: ${project.artifactId:opportunityService}

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: opportunityservice
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
# Ribbon Configurations
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
  redis:
    host: ${vcap.services.rediscloud.credentials.host:redis}
    port: ${vcap.services.rediscloud.credentials.port:6379}
    password: ${vcap.services.rediscloud.credentials.password}
eureka:
  instance:
    onSecurePortEnabled: false
    securePortEnabled: false
    securePort: 8080
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
