server:
  port: ${PORT:0}

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    configprops:
      # keys-to-sanitize:  password # suffix or regex
      keys-to-sanitize: "password,secret"
      # pwd,uid,password,secret,key,client_id,client_key # suffix or regex
    env:
      keys-to-sanitize: "password,secret"
      # password,secret,key,token,.*credentials.*,vcap_services # suffix or regex
# password,secret,key,token,.*credentials.*,vcap_services

logging:
  level:
    com.netflix.eureka: ERROR
    com.netflix.discovery: ERROR
    org.springframework.cloud: ERROR
    io.pivotal.sfdc: DEBUG

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379
  sleuth.sampler.rate: 100
  sleuth.sampler.probability: 1.0
  zipkin.compression.enabled: true
  zipkin.baseUrl: http://wavefront-proxy.wavefront.svc.cluster.local:9411
  zipkin.sender.type: web
  # zipkin.sender.type: rabbit
  # rabbitmq.listener.direct.retry.enabled: true
  # rabbitmq.listener.simple.retry.enabled: true

eureka:
  instance:
    preferIpAddress: true
    hostname: opportunityservice
    nonSecurePort: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:discovery}:8761/eureka/
ribbon:
  IsSecure: false

management.metrics:
  enable.all: true
  export.wavefront:
    source: opportunityservice
    enabled: true
    uri: proxy://wavefront-proxy.wavefront.svc.cluster.local:2878
    step: 10s
  web.server.request.autotime.enabled: true

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: direct
  redis:
    host: ${vcap.services.cache-service.credentials.host:redis}
    port: ${vcap.services.cache-service.credentials.port:6379}
    password: ${vcap.services.cache-service.credentials.password}
  rabbitmq:
    addresses: ${vcap.services.event-bus.credentials.uri}
    # host: ${vcap.services.event-bus.credentials.hostname}
    # port: ${vcap.services.event-bus.credentials.port}
    # virtual-host: ${vcap.services.event-bus.credentials.vhost}
    # username: ${vcap.services.event-bus.credentials.username}
    # password: ${vcap.services.event-bus.credentials.password}
    ssl.enabled: ${vcap.services.event-bus.credentials.ssl}
    ssl.algorithm: TLSv1.2
  sleuth.sampler.rate: 100
  sleuth.sampler.probability: 1.0
  zipkin.compression.enabled: true
  zipkin.baseUrl: https://${vcap.services.wf-proxy.credentials.hostname}:9411
  zipkin.sender.type: web
  # zipkin.sender.type: rabbit
  # rabbitmq.listener.direct.retry.enabled: true
  # rabbitmq.listener.simple.retry.enabled: true

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: 8080
    securePortEnabled: true
    securePort: 61001
    hostname: ${vcap.application.uris[0]}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    healthcheck:
      enabled: true
ribbon:
  IsSecure: true
management.metrics:
  enable.all: true
  export.wavefront:
    source: opportunityservice
    enabled: true
    uri: proxy://${vcap.services.wf-proxy.credentials.hostname}:${vcap.services.wf-proxy.credentials.port}
    step: 10s
  web.server.request.autotime.enabled: true
